### ISSUE TITLE
RebirthDB organization

### ISSUE THREAD

**Issue by thelinuxlich** [crrobinson14/vue-rethinkdb#3]
Hey @crrobinson14 ! We've forked RethinkDB because of the lack of updates and things are moving fast. We always take a look at cool active projects using RethinkDB to ask if they would like to join our organization, what do you think?

**Comment by crrobinson14** [comment]
Anhything that helps get RethinkDB going again is good in my book.

**Comment by thelinuxlich** [comment]
Cool! Communication is officially going here: https://spectrum.chat/rebirthdb

I will add you to the github org

**Comment by crrobinson14** [comment]
Thanks Alisson!

What's the best place for me to help contribute?

**Comment by thelinuxlich** [comment]
Take a look at the topics we are discussing in Spectrum, and if you like you can move this project to our org, when the new site is launched, we will make sure this gets more visibility

**Comment by crrobinson14** [comment]
Cleaning up old tickets. That chat is no longer valid. Some new RethinkDB work is going on, but it doesn't look like there's still a push to have this module "join" the project officially. Please open a new ticket if that changes.
