### ISSUE TITLE
Cannot connect to websocket

### ISSUE THREAD

**Issue by tsujp** [crrobinson14/vue-rethinkdb#5]
I am using the default setup with the only change being inside my vue app with the IP and port of the remote socketcluster, apart from that no changes and I cannot connect to the websocket on my remote.

```
Vue.use(RethinkDB, {
   url: 'ws://[IP]:445',
   log: console
})
```

```
Firefox can’t establish a connection to the server at ws://[IP]:445/. app.js line 1899 > eval:467:22
The connection to ws://[IP]:445/ was interrupted while the page was loading.
```

**Comment by tvld** [comment]
Have you tried ``url: 'wss://[IP]:445'`` ?

**Comment by hito** [comment]
Also doesn't work.

**Comment by tvld** [comment]
I am using the normal https connection  with ports. But admit I did not look at it for more than a year. Going through my old code found these ports:
 ```
- 29015 - Listening for intracluster connections
- 28015 - rethinkdb_1  | Listening for client driver connections
- 8900 - rethinkdb_1  | Webadmin
```

**Comment by altamiranoesdras** [comment]
WebSocket connection to 'ws://localhost:8000/' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by crrobinson14** [comment]
Cleaning up old tickets to re-activate this project. This doesn't look like something I can resolve, or related to this library. We just use a standard Websocket connection to the remote host. If the Websocket can't connect, it's something on that end or in between (load balancer config).
