### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by litti** [crrobinson14/vue-rethinkdb#6]
Since rethinkDB has risen from the dead again and we intend to use a VueJS frontend I'm interested in trying this connection to rethinkDB. Unfortunately I can't find a license. Can you tell me the license which is used for this project or add it to the repo? Thanks a lot in advance!

**Comment by crrobinson14** [comment]
The license is defined by the `license` tag in `package.json` as ISC, but good point. I added the LICENSE file as well to make it clear.
